name: Server Monitor

on:
  schedule:
    - cron: "*/5 * * * *"  # Запуск каждые 5 минут
  workflow_dispatch:       # Возможность ручного запуска

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: 🛠️ Клонируем репозиторий
        uses: actions/checkout@v3

      - name: 🔑 Настраиваем права на скрипт
        run: chmod +x monitoring/check_sites.sh

      - name: 🚀 Запускаем мониторинг
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: monitoring/check_sites.sh

      - name: 📂 Сохраняем обновлённый статус сайтов
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "🔄 Обновление статуса сайтов"
          branch: main
          file_pattern: monitoring/site_status.log
