name: Server Monitor

on:
  schedule:
    - cron: "*/5 * * * *"  # Запуск каждые 5 минут
  workflow_dispatch:       # Возможность ручного запуска

jobs:
  monitor:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Разрешаем Actions делать git push

    steps:
      - name: 🛠️ Клонируем репозиторий
        uses: actions/checkout@v3
        with:
          persist-credentials: true  # Сохраняем авторизацию для git push

      - name: 🔑 Настраиваем права на скрипт
        run: chmod +x monitoring/check_sites.sh

      - name: 🚀 Запускаем мониторинг
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: monitoring/check_sites.sh

      - name: 📂 Подготавливаем изменения перед коммитом
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git pull --rebase  # 🔥 Обновляем локальную копию, чтобы избежать конфликта
          git add monitoring/site_status.log
          git commit -m "🔄 Обновление статуса сайтов" || echo "Нет изменений для коммита"
          git push
